services:
  postgresql:
    image: postgres:16
    ports:
      - "5050:5050"
    environment:
      POSTGRES_DB: rfc_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgresql:/var/lib/postgresql/data
    networks:
      - backend

  liquibase-migrations:
    image: liquibase/liquibase:4.25
    depends_on:
      - postgresql
    command:
      - --changelog-file=db.changelog-master.xml
      - --driver=org.postgresql.Driver
      - --url=jdbc:postgresql://postgresql:5050/rfc_db
      - --username=postgres
      - --password=postgres
      - update
    volumes:
      - ./src/main/resources/db/changelog:/liquibase/changelog
    networks:
      - backend

volumes:
  postgresql: { }
  kafka_data: { }

networks:
  backend: { }
