services:
  db:
    image: postgres:16
    container_name: cab_db
    environment:
      POSTGRES_DB: cab_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    ports:
      - "5050:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - cab-network
    restart: unless-stopped

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.2
    container_name: cab_keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_ENABLED: true
      KC_DEV_FILE_ROOT_PATH: /opt/keycloak/data/import
    ports:
      - "8081:8080"
    volumes:
      - keycloak_data:/opt/keycloak/data
      - ./deploy/keycloak:/opt/keycloak/data/import
    networks:
      - cab-network
    restart: unless-stopped
    command: [ "start-dev" ]

networks:
  cab-network:
    driver: bridge
    name: cab-network

volumes:
  postgres_data:
    name: cab_postgres_data
  keycloak_data:
    name: cab_keycloak_data


